### ISSUE TITLE
rspamd 1.6.5 not in COPR

### ISSUE THREAD

**Issue by danielrenninghoff** [LorbusChris/rspamd-rpm#1]
Hi, thank you very much for your copr repo for rspamd. 👍 

By now, rspamd 1.6.5 has been released. Could you update the version in the COPR?

**Comment by LorbusChris** [comment]
Thank you for the notification! The COPR build has been updated.

Please test :)

**Comment by danielrenninghoff** [comment]
Thank you very much! :)
