### ISSUE TITLE
Update to 2.4

### ISSUE THREAD

**Issue by judemille** [LorbusChris/rspamd-rpm#16]
The current version in the COPR repo is 2.2.2, but the latest rspamd version is 2.4.2. Can you please update this?

**Comment by LorbusChris** [comment]
A new COPR build has been triggered! https://copr.fedorainfracloud.org/coprs/lorbus/rspamd/build/1291477/

**Comment by LorbusChris** [comment]
Looks like the build failed because the rspamd-secure-ssl-ciphers.patch couldn't be applied.
It probably just needs to be updated again to account for more recent changes.

**Comment by LorbusChris** [comment]
Thank you @juliandemille! 2.4 builds have now been completed successfully!
