### ISSUE TITLE
Is the Fedora package still available ?

### ISSUE THREAD

**Issue by pipiche38** [LorbusChris/rspamd-rpm#22]
Trying to update my mail server thoses days and I'm getting an error during the dnf update

```
Copr repo for rspamd owned by lorbus                                                                                                                                                                  578  B/s | 341  B     00:00
Errors during downloading metadata for repository 'copr:copr.fedorainfracloud.org:lorbus:rspamd':
  - Status code: 404 for https://copr-be.cloud.fedoraproject.org/results/lorbus/rspamd/fedora-33-x86_64/repodata/repomd.xml (IP: 52.44.175.77)
Error: Failed to download metadata for repo 'copr:copr.fedorainfracloud.org:lorbus:rspamd': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
Ignoring repositories: copr:copr.fedorainfracloud.org:lorbus:rspamd
```

**Comment by dimejo** [comment]
I suppose the package was removed because Fedora 33 is EOL.

**Comment by LorbusChris** [comment]
Yes, EOL'd packages are removed from COPR automatically. Builds for Fedora 34 and 35 are still available at v2.7.1. I haven't gotten around to updating to v3, but shall do that soon for F34+

**Comment by LorbusChris** [comment]
I've pushed an update for v3.1, it's building on COPR now. Unfortunately F36+ builds have failed in testing, F35 builds fine though

**Comment by LorbusChris** [comment]
For reference: https://copr.fedorainfracloud.org/coprs/lorbus/rspamd/build/3610757/
