### ISSUE TITLE
COPR build fails with F36+

### ISSUE THREAD

**Issue by LorbusChris** [LorbusChris/rspamd-rpm#24]
see e.g. https://copr.fedorainfracloud.org/coprs/lorbus/rspamd/build/3652731/

**Comment by LorbusChris** [comment]
My guess is that it's probably related to GCC 12

**Comment by ajayramaswamy** [comment]
I tried the patch in this bugreport and it works for version 3.2, 3.3 and 3.4 : https://github.com/rspamd/rspamd/pull/4211

but when I go from 3.3 to 3.4 on fedora 37 the program dumps core, do you think you can test and debug any further?


Ok I am not the only one ...
https://github.com/rspamd/rspamd/issues/4329
